=== mickaelgall/XMLCVMICKA/commercial.dtd
<?xml version="1.0" encoding="utf-8">
<!ELEMENT commercial (client+)>
<!ELEMENT client (demande+)>
<!ATTLIST client nom CDATA #REQUIRED>
<!ATTLIST client prenom CDATA #REQUIRED>
<!ATTLIST client mail CDATA #REQUIRED>
<!ATTLIST client mobile CDATA #IMPLIED>
<!ELEMENT demande (destination, periode, duree, nbParticipants, tarifMax, propositions?)>
<!ELEMENT destination (#PCDATA)>
<!ELEMENT periode (#PCDATA)>
<!ELEMENT duree (#PCDATA)>
<!ELEMENT nbParticipants (#PCDATA)>
<!ELEMENT tarifMax (#PCDATA)>
<!ELEMENT propositions (proposition+)>
<!ELEMENT proposition (#PCDATA)>

=== mickaelgall/XMLCVMICKA/commercial.xml
<?xml version="1.0" encoding="utf-8">
<!DOCTYPE commercial SYSTEM "commercial.dtd">
<commercial>
	<client nom="Renard" prenom="Nicolas" mail="nrenard@gmail.com" mobile="0699305567">
		<demande>
			<destination>Mexique</destination>
			<periode>Fin mai 2010</periode>
			<duree>7 nuits</duree>
			<nbParticipants>4</nbParticipants>
			<tarifMax>890.00</tarifMax>
			<propositions>
				<proposition>Circuit Maya</proposition>
				<proposition>Route turquoise....</proposition>
			</propositions>
		</demande>
	</client>
	<client nom="Grenapin" prenom="DorothÃ©e" mail="grenapin@ft-group.com" mobile="0299123455">
	</client>
</commercial>
